const defaultBoardState = {
  items: [
    { column: 1, row: 1, piece: { color: 'black', figure: 'rook' } },
    { column: 2, row: 1, piece: { color: 'black', figure: 'knight' } },
    { column: 3, row: 1, piece: { color: 'black', figure: 'bishop' } },
    { column: 4, row: 1, piece: { color: 'black', figure: 'queen' } },
    { column: 5, row: 1, piece: { color: 'black', figure: 'king' } },
    { column: 6, row: 1, piece: { color: 'black', figure: 'bishop' } },
    { column: 7, row: 1, piece: { color: 'black', figure: 'knight' } },
    { column: 8, row: 1, piece: { color: 'black', figure: 'rook' } },
    { column: 1, row: 2, piece: { color: 'black', figure: 'pawn' } },
    { column: 2, row: 2, piece: { color: 'black', figure: 'pawn' } },
    { column: 3, row: 2, piece: { color: 'black', figure: 'pawn' } },
    { column: 4, row: 2, piece: { color: 'black', figure: 'pawn' } },
    { column: 5, row: 2, piece: { color: 'black', figure: 'pawn' } },
    { column: 6, row: 2, piece: { color: 'black', figure: 'pawn' } },
    { column: 7, row: 2, piece: { color: 'black', figure: 'pawn' } },
    { column: 8, row: 2, piece: { color: 'black', figure: 'pawn' } },
    { column: 1, row: 7, piece: { color: 'white', figure: 'pawn' } },
    { column: 2, row: 7, piece: { color: 'white', figure: 'pawn' } },
    { column: 3, row: 7, piece: { color: 'white', figure: 'pawn' } },
    { column: 4, row: 7, piece: { color: 'white', figure: 'pawn' } },
    { column: 5, row: 7, piece: { color: 'white', figure: 'pawn' } },
    { column: 6, row: 7, piece: { color: 'white', figure: 'pawn' } },
    { column: 7, row: 7, piece: { color: 'white', figure: 'pawn' } },
    { column: 8, row: 7, piece: { color: 'white', figure: 'pawn' } },
    { column: 1, row: 8, piece: { color: 'white', figure: 'rook' } },
    { column: 2, row: 8, piece: { color: 'white', figure: 'knight' } },
    { column: 3, row: 8, piece: { color: 'white', figure: 'bishop' } },
    { column: 4, row: 8, piece: { color: 'white', figure: 'queen' } },
    { column: 5, row: 8, piece: { color: 'white', figure: 'king' } },
    { column: 6, row: 8, piece: { color: 'white', figure: 'bishop' } },
    { column: 7, row: 8, piece: { color: 'white', figure: 'knight' } },
    { column: 8, row: 8, piece: { color: 'white', figure: 'rook' } },
  ],
  player: 'white',
  select: null,
  selectedPiece: [],
  moves: [],
  check: false,
  winner: null,
  promotion: null,
  addPiece: () => {},
  removePiece: () => {},
  selectBoxes: () => {},
  addMove: () => {},
  endGame: () => {},
  restart: () => {},
  promotionPopUp: () => {},
  endPromotion: () => {},
  endTurn: () => {},
};

export default defaultBoardState;
